apiVersion: v1
kind: Pod
metadata:
  name: redis-test-pod
spec:
  containers:
  - name: redis-test-container
    image: python:3.9-slim
    command: ["python", "-c"]
    args:
    - |
      import redis
      import time

      # Connect to Redis
      redis_host = '10.60.0.5'  
      redis_port = 6379

      try:
          r = redis.StrictRedis(host=redis_host, port=redis_port, decode_responses=True)

          # Set a key
          r.set('test_key', 'test_value')

          # Get a key
          value = r.get('test_key')
          print("Retrieved value:", value)

          # Wait for 5 seconds
          time.sleep(5)

          # Delete the key
          r.delete('test_key')
          print("Key deleted successfully")
      except Exception as e:
          print("An error occurred:", e)
