apiVersion: v1
kind: Pod
metadata:
  name: redis-test-pod
spec:
  containers:
  - name: redis-test-container
    image: redis:latest
    command: ["sleep", "3600"]  

    # once this is deployed, exec in the pod and 
    # run apt update and 
    #apt install redis-tools
    #connect to the memory redis cluster and ping
    #should receive pong